package com.dagather.fonme.wallet.dao;

import com.dagather.fonme.wallet.model.UserBillRecharge;
import com.dagather.fonme.wallet.model.UserBillRechargeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBillRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int countByExample(UserBillRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int deleteByExample(UserBillRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ubrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int insert(UserBillRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int insertSelective(UserBillRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    List<UserBillRecharge> selectByExample(UserBillRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    UserBillRecharge selectByPrimaryKey(Long ubrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserBillRecharge record, @Param("example") UserBillRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserBillRecharge record, @Param("example") UserBillRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBillRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBillRecharge record);
}