package com.dagather.fonme.exchange.model;

import java.io.Serializable;
import java.util.Date;

public class ExCurrencyInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_info.eciid
     *
     * @mbggenerated
     */
    private Long eciid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_info.currency_name_zh
     *
     * @mbggenerated
     */
    private String currencyNameZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_info.currency_name_en
     *
     * @mbggenerated
     */
    private String currencyNameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_info.currency_code
     *
     * @mbggenerated
     */
    private String currencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_info.flag_enable
     *
     * @mbggenerated
     */
    private Integer flagEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_info.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_info.eciid
     *
     * @return the value of fm_ex_currency_info.eciid
     *
     * @mbggenerated
     */
    public Long getEciid() {
        return eciid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_info.eciid
     *
     * @param eciid the value for fm_ex_currency_info.eciid
     *
     * @mbggenerated
     */
    public void setEciid(Long eciid) {
        this.eciid = eciid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_info.currency_name_zh
     *
     * @return the value of fm_ex_currency_info.currency_name_zh
     *
     * @mbggenerated
     */
    public String getCurrencyNameZh() {
        return currencyNameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_info.currency_name_zh
     *
     * @param currencyNameZh the value for fm_ex_currency_info.currency_name_zh
     *
     * @mbggenerated
     */
    public void setCurrencyNameZh(String currencyNameZh) {
        this.currencyNameZh = currencyNameZh == null ? null : currencyNameZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_info.currency_name_en
     *
     * @return the value of fm_ex_currency_info.currency_name_en
     *
     * @mbggenerated
     */
    public String getCurrencyNameEn() {
        return currencyNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_info.currency_name_en
     *
     * @param currencyNameEn the value for fm_ex_currency_info.currency_name_en
     *
     * @mbggenerated
     */
    public void setCurrencyNameEn(String currencyNameEn) {
        this.currencyNameEn = currencyNameEn == null ? null : currencyNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_info.currency_code
     *
     * @return the value of fm_ex_currency_info.currency_code
     *
     * @mbggenerated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_info.currency_code
     *
     * @param currencyCode the value for fm_ex_currency_info.currency_code
     *
     * @mbggenerated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_info.flag_enable
     *
     * @return the value of fm_ex_currency_info.flag_enable
     *
     * @mbggenerated
     */
    public Integer getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_info.flag_enable
     *
     * @param flagEnable the value for fm_ex_currency_info.flag_enable
     *
     * @mbggenerated
     */
    public void setFlagEnable(Integer flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_info.create_date
     *
     * @return the value of fm_ex_currency_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_info.create_date
     *
     * @param createDate the value for fm_ex_currency_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_info.update_date
     *
     * @return the value of fm_ex_currency_info.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_info.update_date
     *
     * @param updateDate the value for fm_ex_currency_info.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExCurrencyInfo other = (ExCurrencyInfo) that;
        return (this.getEciid() == null ? other.getEciid() == null : this.getEciid().equals(other.getEciid()))
            && (this.getCurrencyNameZh() == null ? other.getCurrencyNameZh() == null : this.getCurrencyNameZh().equals(other.getCurrencyNameZh()))
            && (this.getCurrencyNameEn() == null ? other.getCurrencyNameEn() == null : this.getCurrencyNameEn().equals(other.getCurrencyNameEn()))
            && (this.getCurrencyCode() == null ? other.getCurrencyCode() == null : this.getCurrencyCode().equals(other.getCurrencyCode()))
            && (this.getFlagEnable() == null ? other.getFlagEnable() == null : this.getFlagEnable().equals(other.getFlagEnable()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEciid() == null) ? 0 : getEciid().hashCode());
        result = prime * result + ((getCurrencyNameZh() == null) ? 0 : getCurrencyNameZh().hashCode());
        result = prime * result + ((getCurrencyNameEn() == null) ? 0 : getCurrencyNameEn().hashCode());
        result = prime * result + ((getCurrencyCode() == null) ? 0 : getCurrencyCode().hashCode());
        result = prime * result + ((getFlagEnable() == null) ? 0 : getFlagEnable().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eciid=").append(eciid);
        sb.append(", currencyNameZh=").append(currencyNameZh);
        sb.append(", currencyNameEn=").append(currencyNameEn);
        sb.append(", currencyCode=").append(currencyCode);
        sb.append(", flagEnable=").append(flagEnable);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}