package com.dagather.fonme.exchange.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExCurrencyRateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public ExCurrencyRateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEcridIsNull() {
            addCriterion("ecrid is null");
            return (Criteria) this;
        }

        public Criteria andEcridIsNotNull() {
            addCriterion("ecrid is not null");
            return (Criteria) this;
        }

        public Criteria andEcridEqualTo(Long value) {
            addCriterion("ecrid =", value, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridNotEqualTo(Long value) {
            addCriterion("ecrid <>", value, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridGreaterThan(Long value) {
            addCriterion("ecrid >", value, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridGreaterThanOrEqualTo(Long value) {
            addCriterion("ecrid >=", value, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridLessThan(Long value) {
            addCriterion("ecrid <", value, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridLessThanOrEqualTo(Long value) {
            addCriterion("ecrid <=", value, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridIn(List<Long> values) {
            addCriterion("ecrid in", values, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridNotIn(List<Long> values) {
            addCriterion("ecrid not in", values, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridBetween(Long value1, Long value2) {
            addCriterion("ecrid between", value1, value2, "ecrid");
            return (Criteria) this;
        }

        public Criteria andEcridNotBetween(Long value1, Long value2) {
            addCriterion("ecrid not between", value1, value2, "ecrid");
            return (Criteria) this;
        }

        public Criteria andYmdIsNull() {
            addCriterion("ymd is null");
            return (Criteria) this;
        }

        public Criteria andYmdIsNotNull() {
            addCriterion("ymd is not null");
            return (Criteria) this;
        }

        public Criteria andYmdEqualTo(String value) {
            addCriterion("ymd =", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdNotEqualTo(String value) {
            addCriterion("ymd <>", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdGreaterThan(String value) {
            addCriterion("ymd >", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdGreaterThanOrEqualTo(String value) {
            addCriterion("ymd >=", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdLessThan(String value) {
            addCriterion("ymd <", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdLessThanOrEqualTo(String value) {
            addCriterion("ymd <=", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdLike(String value) {
            addCriterion("ymd like", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdNotLike(String value) {
            addCriterion("ymd not like", value, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdIn(List<String> values) {
            addCriterion("ymd in", values, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdNotIn(List<String> values) {
            addCriterion("ymd not in", values, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdBetween(String value1, String value2) {
            addCriterion("ymd between", value1, value2, "ymd");
            return (Criteria) this;
        }

        public Criteria andYmdNotBetween(String value1, String value2) {
            addCriterion("ymd not between", value1, value2, "ymd");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeIsNull() {
            addCriterion("ex_fr_currency_code is null");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeIsNotNull() {
            addCriterion("ex_fr_currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeEqualTo(String value) {
            addCriterion("ex_fr_currency_code =", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeNotEqualTo(String value) {
            addCriterion("ex_fr_currency_code <>", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeGreaterThan(String value) {
            addCriterion("ex_fr_currency_code >", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ex_fr_currency_code >=", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeLessThan(String value) {
            addCriterion("ex_fr_currency_code <", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("ex_fr_currency_code <=", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeLike(String value) {
            addCriterion("ex_fr_currency_code like", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeNotLike(String value) {
            addCriterion("ex_fr_currency_code not like", value, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeIn(List<String> values) {
            addCriterion("ex_fr_currency_code in", values, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeNotIn(List<String> values) {
            addCriterion("ex_fr_currency_code not in", values, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeBetween(String value1, String value2) {
            addCriterion("ex_fr_currency_code between", value1, value2, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExFrCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("ex_fr_currency_code not between", value1, value2, "exFrCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeIsNull() {
            addCriterion("ex_to_currency_code is null");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeIsNotNull() {
            addCriterion("ex_to_currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeEqualTo(String value) {
            addCriterion("ex_to_currency_code =", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeNotEqualTo(String value) {
            addCriterion("ex_to_currency_code <>", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeGreaterThan(String value) {
            addCriterion("ex_to_currency_code >", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ex_to_currency_code >=", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeLessThan(String value) {
            addCriterion("ex_to_currency_code <", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("ex_to_currency_code <=", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeLike(String value) {
            addCriterion("ex_to_currency_code like", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeNotLike(String value) {
            addCriterion("ex_to_currency_code not like", value, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeIn(List<String> values) {
            addCriterion("ex_to_currency_code in", values, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeNotIn(List<String> values) {
            addCriterion("ex_to_currency_code not in", values, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeBetween(String value1, String value2) {
            addCriterion("ex_to_currency_code between", value1, value2, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andExToCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("ex_to_currency_code not between", value1, value2, "exToCurrencyCode");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("rate is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("rate is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(BigDecimal value) {
            addCriterion("rate =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(BigDecimal value) {
            addCriterion("rate <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(BigDecimal value) {
            addCriterion("rate >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(BigDecimal value) {
            addCriterion("rate <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<BigDecimal> values) {
            addCriterion("rate in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<BigDecimal> values) {
            addCriterion("rate not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andReverseRateIsNull() {
            addCriterion("reverse_rate is null");
            return (Criteria) this;
        }

        public Criteria andReverseRateIsNotNull() {
            addCriterion("reverse_rate is not null");
            return (Criteria) this;
        }

        public Criteria andReverseRateEqualTo(BigDecimal value) {
            addCriterion("reverse_rate =", value, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateNotEqualTo(BigDecimal value) {
            addCriterion("reverse_rate <>", value, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateGreaterThan(BigDecimal value) {
            addCriterion("reverse_rate >", value, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reverse_rate >=", value, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateLessThan(BigDecimal value) {
            addCriterion("reverse_rate <", value, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reverse_rate <=", value, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateIn(List<BigDecimal> values) {
            addCriterion("reverse_rate in", values, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateNotIn(List<BigDecimal> values) {
            addCriterion("reverse_rate not in", values, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reverse_rate between", value1, value2, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andReverseRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reverse_rate not between", value1, value2, "reverseRate");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNull() {
            addCriterion("flag_enable is null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNotNull() {
            addCriterion("flag_enable is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableEqualTo(Integer value) {
            addCriterion("flag_enable =", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotEqualTo(Integer value) {
            addCriterion("flag_enable <>", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThan(Integer value) {
            addCriterion("flag_enable >", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag_enable >=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThan(Integer value) {
            addCriterion("flag_enable <", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThanOrEqualTo(Integer value) {
            addCriterion("flag_enable <=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIn(List<Integer> values) {
            addCriterion("flag_enable in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotIn(List<Integer> values) {
            addCriterion("flag_enable not in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableBetween(Integer value1, Integer value2) {
            addCriterion("flag_enable between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("flag_enable not between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}