package com.dagather.fonme.exchange.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ExCurrencyRate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.ecrid
     *
     * @mbggenerated
     */
    private Long ecrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.ymd
     *
     * @mbggenerated
     */
    private String ymd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.ex_fr_currency_code
     *
     * @mbggenerated
     */
    private String exFrCurrencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.ex_to_currency_code
     *
     * @mbggenerated
     */
    private String exToCurrencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.rate
     *
     * @mbggenerated
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.reverse_rate
     *
     * @mbggenerated
     */
    private BigDecimal reverseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.flag_enable
     *
     * @mbggenerated
     */
    private Integer flagEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_currency_rate.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.ecrid
     *
     * @return the value of fm_ex_currency_rate.ecrid
     *
     * @mbggenerated
     */
    public Long getEcrid() {
        return ecrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.ecrid
     *
     * @param ecrid the value for fm_ex_currency_rate.ecrid
     *
     * @mbggenerated
     */
    public void setEcrid(Long ecrid) {
        this.ecrid = ecrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.ymd
     *
     * @return the value of fm_ex_currency_rate.ymd
     *
     * @mbggenerated
     */
    public String getYmd() {
        return ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.ymd
     *
     * @param ymd the value for fm_ex_currency_rate.ymd
     *
     * @mbggenerated
     */
    public void setYmd(String ymd) {
        this.ymd = ymd == null ? null : ymd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.ex_fr_currency_code
     *
     * @return the value of fm_ex_currency_rate.ex_fr_currency_code
     *
     * @mbggenerated
     */
    public String getExFrCurrencyCode() {
        return exFrCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.ex_fr_currency_code
     *
     * @param exFrCurrencyCode the value for fm_ex_currency_rate.ex_fr_currency_code
     *
     * @mbggenerated
     */
    public void setExFrCurrencyCode(String exFrCurrencyCode) {
        this.exFrCurrencyCode = exFrCurrencyCode == null ? null : exFrCurrencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.ex_to_currency_code
     *
     * @return the value of fm_ex_currency_rate.ex_to_currency_code
     *
     * @mbggenerated
     */
    public String getExToCurrencyCode() {
        return exToCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.ex_to_currency_code
     *
     * @param exToCurrencyCode the value for fm_ex_currency_rate.ex_to_currency_code
     *
     * @mbggenerated
     */
    public void setExToCurrencyCode(String exToCurrencyCode) {
        this.exToCurrencyCode = exToCurrencyCode == null ? null : exToCurrencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.rate
     *
     * @return the value of fm_ex_currency_rate.rate
     *
     * @mbggenerated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.rate
     *
     * @param rate the value for fm_ex_currency_rate.rate
     *
     * @mbggenerated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.reverse_rate
     *
     * @return the value of fm_ex_currency_rate.reverse_rate
     *
     * @mbggenerated
     */
    public BigDecimal getReverseRate() {
        return reverseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.reverse_rate
     *
     * @param reverseRate the value for fm_ex_currency_rate.reverse_rate
     *
     * @mbggenerated
     */
    public void setReverseRate(BigDecimal reverseRate) {
        this.reverseRate = reverseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.flag_enable
     *
     * @return the value of fm_ex_currency_rate.flag_enable
     *
     * @mbggenerated
     */
    public Integer getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.flag_enable
     *
     * @param flagEnable the value for fm_ex_currency_rate.flag_enable
     *
     * @mbggenerated
     */
    public void setFlagEnable(Integer flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.create_date
     *
     * @return the value of fm_ex_currency_rate.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.create_date
     *
     * @param createDate the value for fm_ex_currency_rate.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_currency_rate.update_date
     *
     * @return the value of fm_ex_currency_rate.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_currency_rate.update_date
     *
     * @param updateDate the value for fm_ex_currency_rate.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExCurrencyRate other = (ExCurrencyRate) that;
        return (this.getEcrid() == null ? other.getEcrid() == null : this.getEcrid().equals(other.getEcrid()))
            && (this.getYmd() == null ? other.getYmd() == null : this.getYmd().equals(other.getYmd()))
            && (this.getExFrCurrencyCode() == null ? other.getExFrCurrencyCode() == null : this.getExFrCurrencyCode().equals(other.getExFrCurrencyCode()))
            && (this.getExToCurrencyCode() == null ? other.getExToCurrencyCode() == null : this.getExToCurrencyCode().equals(other.getExToCurrencyCode()))
            && (this.getRate() == null ? other.getRate() == null : this.getRate().equals(other.getRate()))
            && (this.getReverseRate() == null ? other.getReverseRate() == null : this.getReverseRate().equals(other.getReverseRate()))
            && (this.getFlagEnable() == null ? other.getFlagEnable() == null : this.getFlagEnable().equals(other.getFlagEnable()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEcrid() == null) ? 0 : getEcrid().hashCode());
        result = prime * result + ((getYmd() == null) ? 0 : getYmd().hashCode());
        result = prime * result + ((getExFrCurrencyCode() == null) ? 0 : getExFrCurrencyCode().hashCode());
        result = prime * result + ((getExToCurrencyCode() == null) ? 0 : getExToCurrencyCode().hashCode());
        result = prime * result + ((getRate() == null) ? 0 : getRate().hashCode());
        result = prime * result + ((getReverseRate() == null) ? 0 : getReverseRate().hashCode());
        result = prime * result + ((getFlagEnable() == null) ? 0 : getFlagEnable().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_rate
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ecrid=").append(ecrid);
        sb.append(", ymd=").append(ymd);
        sb.append(", exFrCurrencyCode=").append(exFrCurrencyCode);
        sb.append(", exToCurrencyCode=").append(exToCurrencyCode);
        sb.append(", rate=").append(rate);
        sb.append(", reverseRate=").append(reverseRate);
        sb.append(", flagEnable=").append(flagEnable);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}