package com.dagather.fonme.exchange.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ExExpensesInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.eeiid
     *
     * @mbggenerated
     */
    private Long eeiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.country_name
     *
     * @mbggenerated
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.country_code
     *
     * @mbggenerated
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.phone_code
     *
     * @mbggenerated
     */
    private String phoneCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.rate_cost
     *
     * @mbggenerated
     */
    private BigDecimal rateCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.currency_code
     *
     * @mbggenerated
     */
    private String currencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.flag_enable
     *
     * @mbggenerated
     */
    private Integer flagEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.rate_cny
     *
     * @mbggenerated
     */
    private BigDecimal rateCny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.rate_usd
     *
     * @mbggenerated
     */
    private BigDecimal rateUsd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_ex_expenses_info.rate_profit
     *
     * @mbggenerated
     */
    private BigDecimal rateProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.eeiid
     *
     * @return the value of fm_ex_expenses_info.eeiid
     *
     * @mbggenerated
     */
    public Long getEeiid() {
        return eeiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.eeiid
     *
     * @param eeiid the value for fm_ex_expenses_info.eeiid
     *
     * @mbggenerated
     */
    public void setEeiid(Long eeiid) {
        this.eeiid = eeiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.country_name
     *
     * @return the value of fm_ex_expenses_info.country_name
     *
     * @mbggenerated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.country_name
     *
     * @param countryName the value for fm_ex_expenses_info.country_name
     *
     * @mbggenerated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.country_code
     *
     * @return the value of fm_ex_expenses_info.country_code
     *
     * @mbggenerated
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.country_code
     *
     * @param countryCode the value for fm_ex_expenses_info.country_code
     *
     * @mbggenerated
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.phone_code
     *
     * @return the value of fm_ex_expenses_info.phone_code
     *
     * @mbggenerated
     */
    public String getPhoneCode() {
        return phoneCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.phone_code
     *
     * @param phoneCode the value for fm_ex_expenses_info.phone_code
     *
     * @mbggenerated
     */
    public void setPhoneCode(String phoneCode) {
        this.phoneCode = phoneCode == null ? null : phoneCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.rate_cost
     *
     * @return the value of fm_ex_expenses_info.rate_cost
     *
     * @mbggenerated
     */
    public BigDecimal getRateCost() {
        return rateCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.rate_cost
     *
     * @param rateCost the value for fm_ex_expenses_info.rate_cost
     *
     * @mbggenerated
     */
    public void setRateCost(BigDecimal rateCost) {
        this.rateCost = rateCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.currency_code
     *
     * @return the value of fm_ex_expenses_info.currency_code
     *
     * @mbggenerated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.currency_code
     *
     * @param currencyCode the value for fm_ex_expenses_info.currency_code
     *
     * @mbggenerated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.flag_enable
     *
     * @return the value of fm_ex_expenses_info.flag_enable
     *
     * @mbggenerated
     */
    public Integer getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.flag_enable
     *
     * @param flagEnable the value for fm_ex_expenses_info.flag_enable
     *
     * @mbggenerated
     */
    public void setFlagEnable(Integer flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.create_date
     *
     * @return the value of fm_ex_expenses_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.create_date
     *
     * @param createDate the value for fm_ex_expenses_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.update_date
     *
     * @return the value of fm_ex_expenses_info.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.update_date
     *
     * @param updateDate the value for fm_ex_expenses_info.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.rate_cny
     *
     * @return the value of fm_ex_expenses_info.rate_cny
     *
     * @mbggenerated
     */
    public BigDecimal getRateCny() {
        return rateCny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.rate_cny
     *
     * @param rateCny the value for fm_ex_expenses_info.rate_cny
     *
     * @mbggenerated
     */
    public void setRateCny(BigDecimal rateCny) {
        this.rateCny = rateCny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.rate_usd
     *
     * @return the value of fm_ex_expenses_info.rate_usd
     *
     * @mbggenerated
     */
    public BigDecimal getRateUsd() {
        return rateUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.rate_usd
     *
     * @param rateUsd the value for fm_ex_expenses_info.rate_usd
     *
     * @mbggenerated
     */
    public void setRateUsd(BigDecimal rateUsd) {
        this.rateUsd = rateUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_ex_expenses_info.rate_profit
     *
     * @return the value of fm_ex_expenses_info.rate_profit
     *
     * @mbggenerated
     */
    public BigDecimal getRateProfit() {
        return rateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_ex_expenses_info.rate_profit
     *
     * @param rateProfit the value for fm_ex_expenses_info.rate_profit
     *
     * @mbggenerated
     */
    public void setRateProfit(BigDecimal rateProfit) {
        this.rateProfit = rateProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ExExpensesInfo other = (ExExpensesInfo) that;
        return (this.getEeiid() == null ? other.getEeiid() == null : this.getEeiid().equals(other.getEeiid()))
            && (this.getCountryName() == null ? other.getCountryName() == null : this.getCountryName().equals(other.getCountryName()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getPhoneCode() == null ? other.getPhoneCode() == null : this.getPhoneCode().equals(other.getPhoneCode()))
            && (this.getRateCost() == null ? other.getRateCost() == null : this.getRateCost().equals(other.getRateCost()))
            && (this.getCurrencyCode() == null ? other.getCurrencyCode() == null : this.getCurrencyCode().equals(other.getCurrencyCode()))
            && (this.getFlagEnable() == null ? other.getFlagEnable() == null : this.getFlagEnable().equals(other.getFlagEnable()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getRateCny() == null ? other.getRateCny() == null : this.getRateCny().equals(other.getRateCny()))
            && (this.getRateUsd() == null ? other.getRateUsd() == null : this.getRateUsd().equals(other.getRateUsd()))
            && (this.getRateProfit() == null ? other.getRateProfit() == null : this.getRateProfit().equals(other.getRateProfit()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEeiid() == null) ? 0 : getEeiid().hashCode());
        result = prime * result + ((getCountryName() == null) ? 0 : getCountryName().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getPhoneCode() == null) ? 0 : getPhoneCode().hashCode());
        result = prime * result + ((getRateCost() == null) ? 0 : getRateCost().hashCode());
        result = prime * result + ((getCurrencyCode() == null) ? 0 : getCurrencyCode().hashCode());
        result = prime * result + ((getFlagEnable() == null) ? 0 : getFlagEnable().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getRateCny() == null) ? 0 : getRateCny().hashCode());
        result = prime * result + ((getRateUsd() == null) ? 0 : getRateUsd().hashCode());
        result = prime * result + ((getRateProfit() == null) ? 0 : getRateProfit().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eeiid=").append(eeiid);
        sb.append(", countryName=").append(countryName);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", phoneCode=").append(phoneCode);
        sb.append(", rateCost=").append(rateCost);
        sb.append(", currencyCode=").append(currencyCode);
        sb.append(", flagEnable=").append(flagEnable);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", rateCny=").append(rateCny);
        sb.append(", rateUsd=").append(rateUsd);
        sb.append(", rateProfit=").append(rateProfit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}