package com.dagather.fonme.exchange.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExExpensesInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public ExExpensesInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEeiidIsNull() {
            addCriterion("eeiid is null");
            return (Criteria) this;
        }

        public Criteria andEeiidIsNotNull() {
            addCriterion("eeiid is not null");
            return (Criteria) this;
        }

        public Criteria andEeiidEqualTo(Long value) {
            addCriterion("eeiid =", value, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidNotEqualTo(Long value) {
            addCriterion("eeiid <>", value, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidGreaterThan(Long value) {
            addCriterion("eeiid >", value, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidGreaterThanOrEqualTo(Long value) {
            addCriterion("eeiid >=", value, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidLessThan(Long value) {
            addCriterion("eeiid <", value, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidLessThanOrEqualTo(Long value) {
            addCriterion("eeiid <=", value, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidIn(List<Long> values) {
            addCriterion("eeiid in", values, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidNotIn(List<Long> values) {
            addCriterion("eeiid not in", values, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidBetween(Long value1, Long value2) {
            addCriterion("eeiid between", value1, value2, "eeiid");
            return (Criteria) this;
        }

        public Criteria andEeiidNotBetween(Long value1, Long value2) {
            addCriterion("eeiid not between", value1, value2, "eeiid");
            return (Criteria) this;
        }

        public Criteria andCountryNameIsNull() {
            addCriterion("country_name is null");
            return (Criteria) this;
        }

        public Criteria andCountryNameIsNotNull() {
            addCriterion("country_name is not null");
            return (Criteria) this;
        }

        public Criteria andCountryNameEqualTo(String value) {
            addCriterion("country_name =", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotEqualTo(String value) {
            addCriterion("country_name <>", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameGreaterThan(String value) {
            addCriterion("country_name >", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameGreaterThanOrEqualTo(String value) {
            addCriterion("country_name >=", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLessThan(String value) {
            addCriterion("country_name <", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLessThanOrEqualTo(String value) {
            addCriterion("country_name <=", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameLike(String value) {
            addCriterion("country_name like", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotLike(String value) {
            addCriterion("country_name not like", value, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameIn(List<String> values) {
            addCriterion("country_name in", values, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotIn(List<String> values) {
            addCriterion("country_name not in", values, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameBetween(String value1, String value2) {
            addCriterion("country_name between", value1, value2, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryNameNotBetween(String value1, String value2) {
            addCriterion("country_name not between", value1, value2, "countryName");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIsNull() {
            addCriterion("country_code is null");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIsNotNull() {
            addCriterion("country_code is not null");
            return (Criteria) this;
        }

        public Criteria andCountryCodeEqualTo(String value) {
            addCriterion("country_code =", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotEqualTo(String value) {
            addCriterion("country_code <>", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeGreaterThan(String value) {
            addCriterion("country_code >", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("country_code >=", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLessThan(String value) {
            addCriterion("country_code <", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLessThanOrEqualTo(String value) {
            addCriterion("country_code <=", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLike(String value) {
            addCriterion("country_code like", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotLike(String value) {
            addCriterion("country_code not like", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIn(List<String> values) {
            addCriterion("country_code in", values, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotIn(List<String> values) {
            addCriterion("country_code not in", values, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeBetween(String value1, String value2) {
            addCriterion("country_code between", value1, value2, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotBetween(String value1, String value2) {
            addCriterion("country_code not between", value1, value2, "countryCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeIsNull() {
            addCriterion("phone_code is null");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeIsNotNull() {
            addCriterion("phone_code is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeEqualTo(String value) {
            addCriterion("phone_code =", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeNotEqualTo(String value) {
            addCriterion("phone_code <>", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeGreaterThan(String value) {
            addCriterion("phone_code >", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeGreaterThanOrEqualTo(String value) {
            addCriterion("phone_code >=", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeLessThan(String value) {
            addCriterion("phone_code <", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeLessThanOrEqualTo(String value) {
            addCriterion("phone_code <=", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeLike(String value) {
            addCriterion("phone_code like", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeNotLike(String value) {
            addCriterion("phone_code not like", value, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeIn(List<String> values) {
            addCriterion("phone_code in", values, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeNotIn(List<String> values) {
            addCriterion("phone_code not in", values, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeBetween(String value1, String value2) {
            addCriterion("phone_code between", value1, value2, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andPhoneCodeNotBetween(String value1, String value2) {
            addCriterion("phone_code not between", value1, value2, "phoneCode");
            return (Criteria) this;
        }

        public Criteria andRateCostIsNull() {
            addCriterion("rate_cost is null");
            return (Criteria) this;
        }

        public Criteria andRateCostIsNotNull() {
            addCriterion("rate_cost is not null");
            return (Criteria) this;
        }

        public Criteria andRateCostEqualTo(BigDecimal value) {
            addCriterion("rate_cost =", value, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostNotEqualTo(BigDecimal value) {
            addCriterion("rate_cost <>", value, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostGreaterThan(BigDecimal value) {
            addCriterion("rate_cost >", value, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_cost >=", value, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostLessThan(BigDecimal value) {
            addCriterion("rate_cost <", value, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_cost <=", value, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostIn(List<BigDecimal> values) {
            addCriterion("rate_cost in", values, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostNotIn(List<BigDecimal> values) {
            addCriterion("rate_cost not in", values, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_cost between", value1, value2, "rateCost");
            return (Criteria) this;
        }

        public Criteria andRateCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_cost not between", value1, value2, "rateCost");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNull() {
            addCriterion("currency_code is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIsNotNull() {
            addCriterion("currency_code is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeEqualTo(String value) {
            addCriterion("currency_code =", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotEqualTo(String value) {
            addCriterion("currency_code <>", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThan(String value) {
            addCriterion("currency_code >", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("currency_code >=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThan(String value) {
            addCriterion("currency_code <", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLessThanOrEqualTo(String value) {
            addCriterion("currency_code <=", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeLike(String value) {
            addCriterion("currency_code like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotLike(String value) {
            addCriterion("currency_code not like", value, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeIn(List<String> values) {
            addCriterion("currency_code in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotIn(List<String> values) {
            addCriterion("currency_code not in", values, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeBetween(String value1, String value2) {
            addCriterion("currency_code between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andCurrencyCodeNotBetween(String value1, String value2) {
            addCriterion("currency_code not between", value1, value2, "currencyCode");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNull() {
            addCriterion("flag_enable is null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIsNotNull() {
            addCriterion("flag_enable is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEnableEqualTo(Integer value) {
            addCriterion("flag_enable =", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotEqualTo(Integer value) {
            addCriterion("flag_enable <>", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThan(Integer value) {
            addCriterion("flag_enable >", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag_enable >=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThan(Integer value) {
            addCriterion("flag_enable <", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableLessThanOrEqualTo(Integer value) {
            addCriterion("flag_enable <=", value, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableIn(List<Integer> values) {
            addCriterion("flag_enable in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotIn(List<Integer> values) {
            addCriterion("flag_enable not in", values, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableBetween(Integer value1, Integer value2) {
            addCriterion("flag_enable between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andFlagEnableNotBetween(Integer value1, Integer value2) {
            addCriterion("flag_enable not between", value1, value2, "flagEnable");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andRateCnyIsNull() {
            addCriterion("rate_cny is null");
            return (Criteria) this;
        }

        public Criteria andRateCnyIsNotNull() {
            addCriterion("rate_cny is not null");
            return (Criteria) this;
        }

        public Criteria andRateCnyEqualTo(BigDecimal value) {
            addCriterion("rate_cny =", value, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyNotEqualTo(BigDecimal value) {
            addCriterion("rate_cny <>", value, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyGreaterThan(BigDecimal value) {
            addCriterion("rate_cny >", value, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_cny >=", value, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyLessThan(BigDecimal value) {
            addCriterion("rate_cny <", value, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_cny <=", value, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyIn(List<BigDecimal> values) {
            addCriterion("rate_cny in", values, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyNotIn(List<BigDecimal> values) {
            addCriterion("rate_cny not in", values, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_cny between", value1, value2, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateCnyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_cny not between", value1, value2, "rateCny");
            return (Criteria) this;
        }

        public Criteria andRateUsdIsNull() {
            addCriterion("rate_usd is null");
            return (Criteria) this;
        }

        public Criteria andRateUsdIsNotNull() {
            addCriterion("rate_usd is not null");
            return (Criteria) this;
        }

        public Criteria andRateUsdEqualTo(BigDecimal value) {
            addCriterion("rate_usd =", value, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdNotEqualTo(BigDecimal value) {
            addCriterion("rate_usd <>", value, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdGreaterThan(BigDecimal value) {
            addCriterion("rate_usd >", value, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_usd >=", value, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdLessThan(BigDecimal value) {
            addCriterion("rate_usd <", value, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_usd <=", value, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdIn(List<BigDecimal> values) {
            addCriterion("rate_usd in", values, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdNotIn(List<BigDecimal> values) {
            addCriterion("rate_usd not in", values, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_usd between", value1, value2, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateUsdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_usd not between", value1, value2, "rateUsd");
            return (Criteria) this;
        }

        public Criteria andRateProfitIsNull() {
            addCriterion("rate_profit is null");
            return (Criteria) this;
        }

        public Criteria andRateProfitIsNotNull() {
            addCriterion("rate_profit is not null");
            return (Criteria) this;
        }

        public Criteria andRateProfitEqualTo(BigDecimal value) {
            addCriterion("rate_profit =", value, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitNotEqualTo(BigDecimal value) {
            addCriterion("rate_profit <>", value, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitGreaterThan(BigDecimal value) {
            addCriterion("rate_profit >", value, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_profit >=", value, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitLessThan(BigDecimal value) {
            addCriterion("rate_profit <", value, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rate_profit <=", value, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitIn(List<BigDecimal> values) {
            addCriterion("rate_profit in", values, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitNotIn(List<BigDecimal> values) {
            addCriterion("rate_profit not in", values, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_profit between", value1, value2, "rateProfit");
            return (Criteria) this;
        }

        public Criteria andRateProfitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rate_profit not between", value1, value2, "rateProfit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}