package com.dagather.fonme.wallet.model;

import java.io.Serializable;
import java.util.Date;

public class UserBillCall implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.ubcid
     *
     * @mbggenerated
     */
    private Long ubcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.uwid
     *
     * @mbggenerated
     */
    private Long uwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.uiid
     *
     * @mbggenerated
     */
    private Long uiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.currency_type
     *
     * @mbggenerated
     */
    private Integer currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.callid
     *
     * @mbggenerated
     */
    private String callid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.bind_uuid
     *
     * @mbggenerated
     */
    private String bindUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.caller
     *
     * @mbggenerated
     */
    private String caller;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.callee
     *
     * @mbggenerated
     */
    private String callee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.start_call_time
     *
     * @mbggenerated
     */
    private String startCallTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.start_ring_time
     *
     * @mbggenerated
     */
    private String startRingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.callee_accept_time
     *
     * @mbggenerated
     */
    private String calleeAcceptTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.callee_display_num
     *
     * @mbggenerated
     */
    private String calleeDisplayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.end_call_time
     *
     * @mbggenerated
     */
    private String endCallTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.call_end_reason
     *
     * @mbggenerated
     */
    private String callEndReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.duration
     *
     * @mbggenerated
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.recordfile
     *
     * @mbggenerated
     */
    private String recordfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.flag_enable
     *
     * @mbggenerated
     */
    private Integer flagEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_call.amount_cost
     *
     * @mbggenerated
     */
    private Long amountCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_user_bill_call
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.ubcid
     *
     * @return the value of fm_user_bill_call.ubcid
     *
     * @mbggenerated
     */
    public Long getUbcid() {
        return ubcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.ubcid
     *
     * @param ubcid the value for fm_user_bill_call.ubcid
     *
     * @mbggenerated
     */
    public void setUbcid(Long ubcid) {
        this.ubcid = ubcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.uwid
     *
     * @return the value of fm_user_bill_call.uwid
     *
     * @mbggenerated
     */
    public Long getUwid() {
        return uwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.uwid
     *
     * @param uwid the value for fm_user_bill_call.uwid
     *
     * @mbggenerated
     */
    public void setUwid(Long uwid) {
        this.uwid = uwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.uiid
     *
     * @return the value of fm_user_bill_call.uiid
     *
     * @mbggenerated
     */
    public Long getUiid() {
        return uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.uiid
     *
     * @param uiid the value for fm_user_bill_call.uiid
     *
     * @mbggenerated
     */
    public void setUiid(Long uiid) {
        this.uiid = uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.amount
     *
     * @return the value of fm_user_bill_call.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.amount
     *
     * @param amount the value for fm_user_bill_call.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.currency_type
     *
     * @return the value of fm_user_bill_call.currency_type
     *
     * @mbggenerated
     */
    public Integer getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.currency_type
     *
     * @param currencyType the value for fm_user_bill_call.currency_type
     *
     * @mbggenerated
     */
    public void setCurrencyType(Integer currencyType) {
        this.currencyType = currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.callid
     *
     * @return the value of fm_user_bill_call.callid
     *
     * @mbggenerated
     */
    public String getCallid() {
        return callid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.callid
     *
     * @param callid the value for fm_user_bill_call.callid
     *
     * @mbggenerated
     */
    public void setCallid(String callid) {
        this.callid = callid == null ? null : callid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.app_id
     *
     * @return the value of fm_user_bill_call.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.app_id
     *
     * @param appId the value for fm_user_bill_call.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.bind_uuid
     *
     * @return the value of fm_user_bill_call.bind_uuid
     *
     * @mbggenerated
     */
    public String getBindUuid() {
        return bindUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.bind_uuid
     *
     * @param bindUuid the value for fm_user_bill_call.bind_uuid
     *
     * @mbggenerated
     */
    public void setBindUuid(String bindUuid) {
        this.bindUuid = bindUuid == null ? null : bindUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.caller
     *
     * @return the value of fm_user_bill_call.caller
     *
     * @mbggenerated
     */
    public String getCaller() {
        return caller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.caller
     *
     * @param caller the value for fm_user_bill_call.caller
     *
     * @mbggenerated
     */
    public void setCaller(String caller) {
        this.caller = caller == null ? null : caller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.callee
     *
     * @return the value of fm_user_bill_call.callee
     *
     * @mbggenerated
     */
    public String getCallee() {
        return callee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.callee
     *
     * @param callee the value for fm_user_bill_call.callee
     *
     * @mbggenerated
     */
    public void setCallee(String callee) {
        this.callee = callee == null ? null : callee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.start_call_time
     *
     * @return the value of fm_user_bill_call.start_call_time
     *
     * @mbggenerated
     */
    public String getStartCallTime() {
        return startCallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.start_call_time
     *
     * @param startCallTime the value for fm_user_bill_call.start_call_time
     *
     * @mbggenerated
     */
    public void setStartCallTime(String startCallTime) {
        this.startCallTime = startCallTime == null ? null : startCallTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.start_ring_time
     *
     * @return the value of fm_user_bill_call.start_ring_time
     *
     * @mbggenerated
     */
    public String getStartRingTime() {
        return startRingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.start_ring_time
     *
     * @param startRingTime the value for fm_user_bill_call.start_ring_time
     *
     * @mbggenerated
     */
    public void setStartRingTime(String startRingTime) {
        this.startRingTime = startRingTime == null ? null : startRingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.callee_accept_time
     *
     * @return the value of fm_user_bill_call.callee_accept_time
     *
     * @mbggenerated
     */
    public String getCalleeAcceptTime() {
        return calleeAcceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.callee_accept_time
     *
     * @param calleeAcceptTime the value for fm_user_bill_call.callee_accept_time
     *
     * @mbggenerated
     */
    public void setCalleeAcceptTime(String calleeAcceptTime) {
        this.calleeAcceptTime = calleeAcceptTime == null ? null : calleeAcceptTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.callee_display_num
     *
     * @return the value of fm_user_bill_call.callee_display_num
     *
     * @mbggenerated
     */
    public String getCalleeDisplayNum() {
        return calleeDisplayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.callee_display_num
     *
     * @param calleeDisplayNum the value for fm_user_bill_call.callee_display_num
     *
     * @mbggenerated
     */
    public void setCalleeDisplayNum(String calleeDisplayNum) {
        this.calleeDisplayNum = calleeDisplayNum == null ? null : calleeDisplayNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.end_call_time
     *
     * @return the value of fm_user_bill_call.end_call_time
     *
     * @mbggenerated
     */
    public String getEndCallTime() {
        return endCallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.end_call_time
     *
     * @param endCallTime the value for fm_user_bill_call.end_call_time
     *
     * @mbggenerated
     */
    public void setEndCallTime(String endCallTime) {
        this.endCallTime = endCallTime == null ? null : endCallTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.call_end_reason
     *
     * @return the value of fm_user_bill_call.call_end_reason
     *
     * @mbggenerated
     */
    public String getCallEndReason() {
        return callEndReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.call_end_reason
     *
     * @param callEndReason the value for fm_user_bill_call.call_end_reason
     *
     * @mbggenerated
     */
    public void setCallEndReason(String callEndReason) {
        this.callEndReason = callEndReason == null ? null : callEndReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.duration
     *
     * @return the value of fm_user_bill_call.duration
     *
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.duration
     *
     * @param duration the value for fm_user_bill_call.duration
     *
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.recordfile
     *
     * @return the value of fm_user_bill_call.recordfile
     *
     * @mbggenerated
     */
    public String getRecordfile() {
        return recordfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.recordfile
     *
     * @param recordfile the value for fm_user_bill_call.recordfile
     *
     * @mbggenerated
     */
    public void setRecordfile(String recordfile) {
        this.recordfile = recordfile == null ? null : recordfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.flag_enable
     *
     * @return the value of fm_user_bill_call.flag_enable
     *
     * @mbggenerated
     */
    public Integer getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.flag_enable
     *
     * @param flagEnable the value for fm_user_bill_call.flag_enable
     *
     * @mbggenerated
     */
    public void setFlagEnable(Integer flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.create_date
     *
     * @return the value of fm_user_bill_call.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.create_date
     *
     * @param createDate the value for fm_user_bill_call.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.update_date
     *
     * @return the value of fm_user_bill_call.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.update_date
     *
     * @param updateDate the value for fm_user_bill_call.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_call.amount_cost
     *
     * @return the value of fm_user_bill_call.amount_cost
     *
     * @mbggenerated
     */
    public Long getAmountCost() {
        return amountCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_call.amount_cost
     *
     * @param amountCost the value for fm_user_bill_call.amount_cost
     *
     * @mbggenerated
     */
    public void setAmountCost(Long amountCost) {
        this.amountCost = amountCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_call
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBillCall other = (UserBillCall) that;
        return (this.getUbcid() == null ? other.getUbcid() == null : this.getUbcid().equals(other.getUbcid()))
            && (this.getUwid() == null ? other.getUwid() == null : this.getUwid().equals(other.getUwid()))
            && (this.getUiid() == null ? other.getUiid() == null : this.getUiid().equals(other.getUiid()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCurrencyType() == null ? other.getCurrencyType() == null : this.getCurrencyType().equals(other.getCurrencyType()))
            && (this.getCallid() == null ? other.getCallid() == null : this.getCallid().equals(other.getCallid()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getBindUuid() == null ? other.getBindUuid() == null : this.getBindUuid().equals(other.getBindUuid()))
            && (this.getCaller() == null ? other.getCaller() == null : this.getCaller().equals(other.getCaller()))
            && (this.getCallee() == null ? other.getCallee() == null : this.getCallee().equals(other.getCallee()))
            && (this.getStartCallTime() == null ? other.getStartCallTime() == null : this.getStartCallTime().equals(other.getStartCallTime()))
            && (this.getStartRingTime() == null ? other.getStartRingTime() == null : this.getStartRingTime().equals(other.getStartRingTime()))
            && (this.getCalleeAcceptTime() == null ? other.getCalleeAcceptTime() == null : this.getCalleeAcceptTime().equals(other.getCalleeAcceptTime()))
            && (this.getCalleeDisplayNum() == null ? other.getCalleeDisplayNum() == null : this.getCalleeDisplayNum().equals(other.getCalleeDisplayNum()))
            && (this.getEndCallTime() == null ? other.getEndCallTime() == null : this.getEndCallTime().equals(other.getEndCallTime()))
            && (this.getCallEndReason() == null ? other.getCallEndReason() == null : this.getCallEndReason().equals(other.getCallEndReason()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
            && (this.getRecordfile() == null ? other.getRecordfile() == null : this.getRecordfile().equals(other.getRecordfile()))
            && (this.getFlagEnable() == null ? other.getFlagEnable() == null : this.getFlagEnable().equals(other.getFlagEnable()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getAmountCost() == null ? other.getAmountCost() == null : this.getAmountCost().equals(other.getAmountCost()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_call
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUbcid() == null) ? 0 : getUbcid().hashCode());
        result = prime * result + ((getUwid() == null) ? 0 : getUwid().hashCode());
        result = prime * result + ((getUiid() == null) ? 0 : getUiid().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCurrencyType() == null) ? 0 : getCurrencyType().hashCode());
        result = prime * result + ((getCallid() == null) ? 0 : getCallid().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getBindUuid() == null) ? 0 : getBindUuid().hashCode());
        result = prime * result + ((getCaller() == null) ? 0 : getCaller().hashCode());
        result = prime * result + ((getCallee() == null) ? 0 : getCallee().hashCode());
        result = prime * result + ((getStartCallTime() == null) ? 0 : getStartCallTime().hashCode());
        result = prime * result + ((getStartRingTime() == null) ? 0 : getStartRingTime().hashCode());
        result = prime * result + ((getCalleeAcceptTime() == null) ? 0 : getCalleeAcceptTime().hashCode());
        result = prime * result + ((getCalleeDisplayNum() == null) ? 0 : getCalleeDisplayNum().hashCode());
        result = prime * result + ((getEndCallTime() == null) ? 0 : getEndCallTime().hashCode());
        result = prime * result + ((getCallEndReason() == null) ? 0 : getCallEndReason().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getRecordfile() == null) ? 0 : getRecordfile().hashCode());
        result = prime * result + ((getFlagEnable() == null) ? 0 : getFlagEnable().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getAmountCost() == null) ? 0 : getAmountCost().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_call
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ubcid=").append(ubcid);
        sb.append(", uwid=").append(uwid);
        sb.append(", uiid=").append(uiid);
        sb.append(", amount=").append(amount);
        sb.append(", currencyType=").append(currencyType);
        sb.append(", callid=").append(callid);
        sb.append(", appId=").append(appId);
        sb.append(", bindUuid=").append(bindUuid);
        sb.append(", caller=").append(caller);
        sb.append(", callee=").append(callee);
        sb.append(", startCallTime=").append(startCallTime);
        sb.append(", startRingTime=").append(startRingTime);
        sb.append(", calleeAcceptTime=").append(calleeAcceptTime);
        sb.append(", calleeDisplayNum=").append(calleeDisplayNum);
        sb.append(", endCallTime=").append(endCallTime);
        sb.append(", callEndReason=").append(callEndReason);
        sb.append(", duration=").append(duration);
        sb.append(", recordfile=").append(recordfile);
        sb.append(", flagEnable=").append(flagEnable);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", amountCost=").append(amountCost);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}