package com.dagather.fonme.wallet.model;

import java.io.Serializable;
import java.util.Date;

public class UserWalletDetails implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.uwdid
     *
     * @mbggenerated
     */
    private Long uwdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.uwid
     *
     * @mbggenerated
     */
    private Long uwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.uiid
     *
     * @mbggenerated
     */
    private Long uiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.bill_type
     *
     * @mbggenerated
     */
    private Integer billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.bill_id
     *
     * @mbggenerated
     */
    private Long billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.currency_type
     *
     * @mbggenerated
     */
    private Integer currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.flag_enable
     *
     * @mbggenerated
     */
    private Integer flagEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_wallet_details.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_user_wallet_details
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.uwdid
     *
     * @return the value of fm_user_wallet_details.uwdid
     *
     * @mbggenerated
     */
    public Long getUwdid() {
        return uwdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.uwdid
     *
     * @param uwdid the value for fm_user_wallet_details.uwdid
     *
     * @mbggenerated
     */
    public void setUwdid(Long uwdid) {
        this.uwdid = uwdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.uwid
     *
     * @return the value of fm_user_wallet_details.uwid
     *
     * @mbggenerated
     */
    public Long getUwid() {
        return uwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.uwid
     *
     * @param uwid the value for fm_user_wallet_details.uwid
     *
     * @mbggenerated
     */
    public void setUwid(Long uwid) {
        this.uwid = uwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.uiid
     *
     * @return the value of fm_user_wallet_details.uiid
     *
     * @mbggenerated
     */
    public Long getUiid() {
        return uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.uiid
     *
     * @param uiid the value for fm_user_wallet_details.uiid
     *
     * @mbggenerated
     */
    public void setUiid(Long uiid) {
        this.uiid = uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.amount
     *
     * @return the value of fm_user_wallet_details.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.amount
     *
     * @param amount the value for fm_user_wallet_details.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.bill_type
     *
     * @return the value of fm_user_wallet_details.bill_type
     *
     * @mbggenerated
     */
    public Integer getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.bill_type
     *
     * @param billType the value for fm_user_wallet_details.bill_type
     *
     * @mbggenerated
     */
    public void setBillType(Integer billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.bill_id
     *
     * @return the value of fm_user_wallet_details.bill_id
     *
     * @mbggenerated
     */
    public Long getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.bill_id
     *
     * @param billId the value for fm_user_wallet_details.bill_id
     *
     * @mbggenerated
     */
    public void setBillId(Long billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.currency_type
     *
     * @return the value of fm_user_wallet_details.currency_type
     *
     * @mbggenerated
     */
    public Integer getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.currency_type
     *
     * @param currencyType the value for fm_user_wallet_details.currency_type
     *
     * @mbggenerated
     */
    public void setCurrencyType(Integer currencyType) {
        this.currencyType = currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.flag_enable
     *
     * @return the value of fm_user_wallet_details.flag_enable
     *
     * @mbggenerated
     */
    public Integer getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.flag_enable
     *
     * @param flagEnable the value for fm_user_wallet_details.flag_enable
     *
     * @mbggenerated
     */
    public void setFlagEnable(Integer flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.create_date
     *
     * @return the value of fm_user_wallet_details.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.create_date
     *
     * @param createDate the value for fm_user_wallet_details.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_wallet_details.update_date
     *
     * @return the value of fm_user_wallet_details.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_wallet_details.update_date
     *
     * @param updateDate the value for fm_user_wallet_details.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_wallet_details
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserWalletDetails other = (UserWalletDetails) that;
        return (this.getUwdid() == null ? other.getUwdid() == null : this.getUwdid().equals(other.getUwdid()))
            && (this.getUwid() == null ? other.getUwid() == null : this.getUwid().equals(other.getUwid()))
            && (this.getUiid() == null ? other.getUiid() == null : this.getUiid().equals(other.getUiid()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getBillType() == null ? other.getBillType() == null : this.getBillType().equals(other.getBillType()))
            && (this.getBillId() == null ? other.getBillId() == null : this.getBillId().equals(other.getBillId()))
            && (this.getCurrencyType() == null ? other.getCurrencyType() == null : this.getCurrencyType().equals(other.getCurrencyType()))
            && (this.getFlagEnable() == null ? other.getFlagEnable() == null : this.getFlagEnable().equals(other.getFlagEnable()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_wallet_details
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUwdid() == null) ? 0 : getUwdid().hashCode());
        result = prime * result + ((getUwid() == null) ? 0 : getUwid().hashCode());
        result = prime * result + ((getUiid() == null) ? 0 : getUiid().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getBillType() == null) ? 0 : getBillType().hashCode());
        result = prime * result + ((getBillId() == null) ? 0 : getBillId().hashCode());
        result = prime * result + ((getCurrencyType() == null) ? 0 : getCurrencyType().hashCode());
        result = prime * result + ((getFlagEnable() == null) ? 0 : getFlagEnable().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_wallet_details
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uwdid=").append(uwdid);
        sb.append(", uwid=").append(uwid);
        sb.append(", uiid=").append(uiid);
        sb.append(", amount=").append(amount);
        sb.append(", billType=").append(billType);
        sb.append(", billId=").append(billId);
        sb.append(", currencyType=").append(currencyType);
        sb.append(", flagEnable=").append(flagEnable);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}