package com.dagather.fonme.wallet.model;

import java.io.Serializable;
import java.util.Date;

public class UserBillRecharge implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.ubrid
     *
     * @mbggenerated
     */
    private Long ubrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.uwid
     *
     * @mbggenerated
     */
    private Long uwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.uiid
     *
     * @mbggenerated
     */
    private Long uiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.currency_type
     *
     * @mbggenerated
     */
    private Integer currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.channel_name
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.channel_order_no
     *
     * @mbggenerated
     */
    private String channelOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.channel_order_time
     *
     * @mbggenerated
     */
    private String channelOrderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.flag_enable
     *
     * @mbggenerated
     */
    private Integer flagEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user_bill_recharge.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.ubrid
     *
     * @return the value of fm_user_bill_recharge.ubrid
     *
     * @mbggenerated
     */
    public Long getUbrid() {
        return ubrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.ubrid
     *
     * @param ubrid the value for fm_user_bill_recharge.ubrid
     *
     * @mbggenerated
     */
    public void setUbrid(Long ubrid) {
        this.ubrid = ubrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.uwid
     *
     * @return the value of fm_user_bill_recharge.uwid
     *
     * @mbggenerated
     */
    public Long getUwid() {
        return uwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.uwid
     *
     * @param uwid the value for fm_user_bill_recharge.uwid
     *
     * @mbggenerated
     */
    public void setUwid(Long uwid) {
        this.uwid = uwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.uiid
     *
     * @return the value of fm_user_bill_recharge.uiid
     *
     * @mbggenerated
     */
    public Long getUiid() {
        return uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.uiid
     *
     * @param uiid the value for fm_user_bill_recharge.uiid
     *
     * @mbggenerated
     */
    public void setUiid(Long uiid) {
        this.uiid = uiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.amount
     *
     * @return the value of fm_user_bill_recharge.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.amount
     *
     * @param amount the value for fm_user_bill_recharge.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.currency_type
     *
     * @return the value of fm_user_bill_recharge.currency_type
     *
     * @mbggenerated
     */
    public Integer getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.currency_type
     *
     * @param currencyType the value for fm_user_bill_recharge.currency_type
     *
     * @mbggenerated
     */
    public void setCurrencyType(Integer currencyType) {
        this.currencyType = currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.channel_name
     *
     * @return the value of fm_user_bill_recharge.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.channel_name
     *
     * @param channelName the value for fm_user_bill_recharge.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.channel_order_no
     *
     * @return the value of fm_user_bill_recharge.channel_order_no
     *
     * @mbggenerated
     */
    public String getChannelOrderNo() {
        return channelOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.channel_order_no
     *
     * @param channelOrderNo the value for fm_user_bill_recharge.channel_order_no
     *
     * @mbggenerated
     */
    public void setChannelOrderNo(String channelOrderNo) {
        this.channelOrderNo = channelOrderNo == null ? null : channelOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.channel_order_time
     *
     * @return the value of fm_user_bill_recharge.channel_order_time
     *
     * @mbggenerated
     */
    public String getChannelOrderTime() {
        return channelOrderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.channel_order_time
     *
     * @param channelOrderTime the value for fm_user_bill_recharge.channel_order_time
     *
     * @mbggenerated
     */
    public void setChannelOrderTime(String channelOrderTime) {
        this.channelOrderTime = channelOrderTime == null ? null : channelOrderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.remark
     *
     * @return the value of fm_user_bill_recharge.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.remark
     *
     * @param remark the value for fm_user_bill_recharge.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.flag_enable
     *
     * @return the value of fm_user_bill_recharge.flag_enable
     *
     * @mbggenerated
     */
    public Integer getFlagEnable() {
        return flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.flag_enable
     *
     * @param flagEnable the value for fm_user_bill_recharge.flag_enable
     *
     * @mbggenerated
     */
    public void setFlagEnable(Integer flagEnable) {
        this.flagEnable = flagEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.create_date
     *
     * @return the value of fm_user_bill_recharge.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.create_date
     *
     * @param createDate the value for fm_user_bill_recharge.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user_bill_recharge.update_date
     *
     * @return the value of fm_user_bill_recharge.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user_bill_recharge.update_date
     *
     * @param updateDate the value for fm_user_bill_recharge.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserBillRecharge other = (UserBillRecharge) that;
        return (this.getUbrid() == null ? other.getUbrid() == null : this.getUbrid().equals(other.getUbrid()))
            && (this.getUwid() == null ? other.getUwid() == null : this.getUwid().equals(other.getUwid()))
            && (this.getUiid() == null ? other.getUiid() == null : this.getUiid().equals(other.getUiid()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCurrencyType() == null ? other.getCurrencyType() == null : this.getCurrencyType().equals(other.getCurrencyType()))
            && (this.getChannelName() == null ? other.getChannelName() == null : this.getChannelName().equals(other.getChannelName()))
            && (this.getChannelOrderNo() == null ? other.getChannelOrderNo() == null : this.getChannelOrderNo().equals(other.getChannelOrderNo()))
            && (this.getChannelOrderTime() == null ? other.getChannelOrderTime() == null : this.getChannelOrderTime().equals(other.getChannelOrderTime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getFlagEnable() == null ? other.getFlagEnable() == null : this.getFlagEnable().equals(other.getFlagEnable()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUbrid() == null) ? 0 : getUbrid().hashCode());
        result = prime * result + ((getUwid() == null) ? 0 : getUwid().hashCode());
        result = prime * result + ((getUiid() == null) ? 0 : getUiid().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCurrencyType() == null) ? 0 : getCurrencyType().hashCode());
        result = prime * result + ((getChannelName() == null) ? 0 : getChannelName().hashCode());
        result = prime * result + ((getChannelOrderNo() == null) ? 0 : getChannelOrderNo().hashCode());
        result = prime * result + ((getChannelOrderTime() == null) ? 0 : getChannelOrderTime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getFlagEnable() == null) ? 0 : getFlagEnable().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_bill_recharge
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ubrid=").append(ubrid);
        sb.append(", uwid=").append(uwid);
        sb.append(", uiid=").append(uiid);
        sb.append(", amount=").append(amount);
        sb.append(", currencyType=").append(currencyType);
        sb.append(", channelName=").append(channelName);
        sb.append(", channelOrderNo=").append(channelOrderNo);
        sb.append(", channelOrderTime=").append(channelOrderTime);
        sb.append(", remark=").append(remark);
        sb.append(", flagEnable=").append(flagEnable);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}