package com.dagather.fonme.exchange.dao;

import com.dagather.fonme.exchange.model.ExCurrencyInfo;
import com.dagather.fonme.exchange.model.ExCurrencyInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExCurrencyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int countByExample(ExCurrencyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int deleteByExample(ExCurrencyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long eciid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int insert(ExCurrencyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int insertSelective(ExCurrencyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    List<ExCurrencyInfo> selectByExample(ExCurrencyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    ExCurrencyInfo selectByPrimaryKey(Long eciid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExCurrencyInfo record, @Param("example") ExCurrencyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExCurrencyInfo record, @Param("example") ExCurrencyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExCurrencyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_currency_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExCurrencyInfo record);
}