package com.dagather.fonme.exchange.dao;

import com.dagather.fonme.exchange.model.ExExpensesInfo;
import com.dagather.fonme.exchange.model.ExExpensesInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExExpensesInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int countByExample(ExExpensesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int deleteByExample(ExExpensesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long eeiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int insert(ExExpensesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int insertSelective(ExExpensesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    List<ExExpensesInfo> selectByExample(ExExpensesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    ExExpensesInfo selectByPrimaryKey(Long eeiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExExpensesInfo record, @Param("example") ExExpensesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExExpensesInfo record, @Param("example") ExExpensesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExExpensesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_ex_expenses_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExExpensesInfo record);
}